package com.jing.svg.dataType;

/**
 * Created by jguo on 12/9/2015.
 */
public enum SVGRenderingIntent {
    RENDERING_INTENT_UNKNOWN,
    RENDERING_INTENT_AUTO,
    RENDERING_INTENT_PERCEPTUAL,
    RENDERING_INTENT_RELATIVE_COLORIMETRIC,
    RENDERING_INTENT_SATURATION,
    RENDERING_INTENT_ABSOLUTE_COLORIMETRIC;
}
